import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Terms & Conditions — PanelMind AI",
  description:
    "The terms on which you may use PanelMind AI, including what its marks do and do not mean.",
};

const SECTIONS: LegalSection[] = [
  {
    heading: "1. Who may use this",
    body: [
      "You must be at least sixteen years old and able to enter a binding agreement. One account per person. Do not share your sign-in code with anyone; anything done through your account is treated as done by you.",
    ],
  },
  {
    heading: "2. What the service is",
    body: [
      "PanelMind AI simulates a UPSC-style personality test. A panel of AI interviewers reads a form you supply, questions you aloud, and produces marks and written remarks.",
      "It is a practice tool. It is not a coaching institute, not an assessment authority, and not a predictor of your result.",
    ],
  },
  {
    heading: "3. No affiliation with UPSC",
    body: [
      "PanelMind AI is independent. It is not affiliated with, endorsed by, licensed by, or connected in any way to the Union Public Service Commission or any government body. References to UPSC describe the examination the product prepares you for, nothing more.",
      "Nothing on this site should be read as an official communication of the Commission, and no marks produced here have any official standing.",
    ],
  },
  {
    heading: "4. The marks are not official marks",
    body: [
      "Scores are generated by AI models. They are calibrated to resemble the range real boards award, but they are an estimate produced by software and may be wrong in either direction.",
      "Use them to compare your own attempts over time. Do not treat them as a prediction of your interview score, your rank, or your selection.",
    ],
  },
  {
    heading: "5. Acceptable use",
    body: ["Do not:"],
    list: [
      "Submit another person's application form or personal details as your own.",
      "Attempt to extract prompts, model weights, or the internals of the board.",
      "Scrape, resell, or redistribute questions, transcripts or marking output as your own product.",
      "Use the service to harass anyone, or submit unlawful content.",
      "Interfere with the service's operation or attempt to circumvent limits.",
    ],
  },
  {
    heading: "6. Your content",
    body: [
      "Your DAF and your answers remain yours. You grant us only the licence needed to run the service: to process your form so the board can question you, to transcribe your answers, and to produce and store your marks.",
      "We do not use your interview content to train foundation models.",
    ],
  },
  {
    heading: "7. Our content",
    body: [
      "The interface, the board's design, the marking rubric implementation and the code are ours. You may not copy or reuse them commercially without written permission.",
    ],
  },
  {
    heading: "8. Availability",
    body: [
      "The product is in preview and provided as-is. Interviews depend on third-party speech and language providers, and those can fail. We do not promise uninterrupted service, and a session can end unexpectedly.",
      "If a mock breaks through no fault of yours, tell us and we will re-run or re-mark it.",
    ],
  },
  {
    heading: "9. Limitation of liability",
    body: [
      "To the fullest extent the law allows, we are not liable for indirect or consequential loss, and specifically not for any examination outcome, career decision, or opportunity you attribute to using or not using this product.",
      "Where liability cannot be excluded, it is limited to the amount you have paid us in the twelve months before the claim — which, while the product is free, is nil.",
    ],
  },
  {
    heading: "10. Ending your use",
    body: [
      "You may stop and ask for deletion at any time. We may suspend an account that breaches these terms, and will say why unless we are legally prevented from doing so.",
    ],
  },
  {
    heading: "11. Governing law",
    body: [
      "These terms are governed by the laws of India, and the courts of India have exclusive jurisdiction over any dispute arising from them.",
    ],
  },
  {
    heading: "12. Changes",
    body: [
      "We may revise these terms. Material changes will be noted on this page with a new date. Continuing to use the product after that means you accept the revision.",
    ],
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      current="/terms"
      title="Terms & Conditions"
      updated="1 August 2026"
      intro="The short version: this is a practice tool, its marks are produced by AI and carry no official weight, and it has nothing to do with the Union Public Service Commission. The longer version follows."
      sections={SECTIONS}
    />
  );
}
