import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Disclaimer — PanelMind AI",
  description:
    "What PanelMind AI's marks mean, what they do not mean, and its relationship to the Union Public Service Commission.",
};

const SECTIONS: LegalSection[] = [
  {
    heading: "Not affiliated with UPSC",
    body: [
      "PanelMind AI is a private, independent product. It is not affiliated with, endorsed by, licensed by, or connected to the Union Public Service Commission, the Department of Personnel and Training, or any government body.",
      "We do not conduct any official examination, we cannot influence any official result, and no member of any real board is involved in this product. Where the examination is named, it is to describe what the tool prepares you for.",
    ],
  },
  {
    heading: "The marks are an estimate",
    body: [
      "Every score, trait rating and remark is generated by artificial intelligence. The rubric mirrors the seven traits the Commission publishes, and the scale is calibrated to the range real boards award — but the output is software's judgement, not a board's.",
      "Two runs of the same interview can differ. A mark can be too harsh or too generous. Treat it as a signal about your own progress across attempts, never as a prediction of your interview score, your rank, or your selection.",
    ],
  },
  {
    heading: "No guarantee of any outcome",
    body: [
      "Using this product does not improve your chances of selection in any guaranteed way. We make no claim about ranks, cut-offs, or success rates, and we do not publish selection statistics because we have no way to verify them.",
      "Anyone telling you a mock interview guarantees selection is selling you something. That includes us, if we ever say it.",
    ],
  },
  {
    heading: "Beware of impersonation",
    body: [
      "We will never call or message you claiming to be from UPSC. We will never ask for your Roll Number, DAF credentials on the official portal, Aadhaar, or any payment to 'secure' an interview slot.",
      "Our only channels are this website and hello@panelmind.ai. Anything else claiming to be us is not us — please report it so we can act.",
    ],
  },
  {
    heading: "Content accuracy",
    body: [
      "The board asks factual questions and can be wrong. It may state something inaccurate about your district, your optional subject, or current affairs. Do not treat anything it says as a source. Verify from standard references before you carry it into a real interview.",
    ],
  },
  {
    heading: "Third-party services",
    body: [
      "Interviews depend on external speech and language providers. Their availability, latency and quality are outside our control, and an interview can fail because of them. If that happens to a paid mock, see the refunds page.",
    ],
  },
  {
    heading: "Questions",
    body: [
      "If anything here is unclear, or you think the product has overstated what it can do, write to hello@panelmind.ai. We would rather correct it than defend it.",
    ],
  },
];

export default function DisclaimerPage() {
  return (
    <LegalPage
      current="/disclaimer"
      title="Disclaimer"
      updated="1 August 2026"
      intro="This product simulates a UPSC personality test. It is not the Commission, its marks are not the Commission's marks, and it cannot promise you an outcome. Everything below follows from those three facts."
      sections={SECTIONS}
    />
  );
}
